### PR TITLE
[WIP] Handling of some of Swagger's annotations

### PR DESCRIPTION
**Pull request by hugop95**
#64 

The idea is to add a stage after the library parsing (that creates initial tags, endpoints, etc...), and before starting to build the YAML model, that allows modules (such as the Swagger one) to override those attributes. Ideally, the JavaDoc follows the same principle. If needed tomorrow, this allows users to register their own modules that can override attributes as they please.

- [ ] `@ApiResponses` 
- [x] `@Tag - name`
- [x] `@Tag - description`
- [x] `@Tag - externalDocs`
- [x] `@Operation - summary`
- [x] `@Operation - operationId`
- [x] `@Operation - description`
- [x] `@Operation - externalDocs`
- [x] `@Operation - deprecated`

Will add the rest later.

### CODE REVIEW

**Comment by maksim-pinguin** [comment]
Any updates regarding this?

**Comment by hugop95** [comment]
@maksim-pinguin I'm sorry 😅
I forgot about this PR, I initially started this because it would have been a great improvement in the previous company I was working for, but I have moved away since. 

I wasn't sure if this would be a wanted feature and thought that the changes made were already quite large, so I kind of abandoned it.

I would like to tell you that I could get back to it today, but I'm working on other topics at the moment, so I think that it's objectively dead. 😓

**Comment by hugop95** [comment]
Sorry for the late response, this PR is too far from the base branch to be maintainable anyway, would need to restart from scratch if needed.

**Comment by kbuntrock** [comment]
> Sorry for the late response, this PR is too far from the base branch to be maintainable anyway, would need to restart from scratch if needed.

No worries. Thanks for the work, keeping this in mind to retry it someday.

**Pull request closed without merging**
